### ISSUE TITLE
Only store metadata when post contains an embed

### ISSUE THREAD

**Issue by m4lvin** [documentcloud/wordpress-documentcloud#51]
The meta variable `wide_assets` is added on all posts (even those without documentcloud embeds). Some of my users find this irritating. Could you store this information elsewhere or hide it? Or is it meant to be edited manually?

Alternatively, could you make sure `wide_assets` is only added to posts actually containing documentcloud embeds?

**Comment by reefdog** [comment]
@m4lvin Yeah, I can see that being irritating. We inherited this plugin from @argoproject, and they used this boolean to signal some of their themes. Now that the plugin is meant for more generic use, we should revisit the impact of `wide_assets`.

I'm not caught up on WordPress best practices. What's the better way to store this, and to ensure it's only set if an embed exists? Would you be able to take a crack at it?

@eyeseast or @aschweigert: any idea if the current themes still care about `wide_assets`?

**Comment by m4lvin** [comment]
Thanks for the reply. If extra information per post is really needed, then it should be in a separate table managed by the plugin only. And In the post editor [add_meta_box](https://developer.wordpress.org/reference/functions/add_meta_box/) seems to be the right thing to use?

I will not implement this myself though, because now I realized that oEmbed without any plugin is enough for our purposes. Then the meta variables should not be generated, correct?

**Comment by reefdog** [comment]
Correct, if you don't have this plugin installed, we wouldn't have any facility for storing meta variables. Glad to hear the vanilla oEmbed works for you!

I'm going to reframe the title of this issue, though I don't know if/when I'll be able to get to it. If you *do* want to take a crack, PRs are much apprecated. :)

**Comment by eyeseast** [comment]
Copying over what I wrote before on this:

> The basic idea was that plugin could set a post meta variable saying that it was meant for a wider post format (like a full-width document) and a theme could deal with that. It's meant to be a loose contract, hence settings for normal width and full width.

We had a couple different plugins that implemented `wide_assets`. That's part of why it's in `wp_post_meta` instead of another table. I think that was also just the normal pattern in 2011, to put everything in meta fields. 

I don't know if anyone is still actively developing that theme, but I know several NPR local stations still use it. 

Part of the contract is that the theme should only deal with `wide_assets` if the flag is present, and do nothing in its absence. In theory, it should be safe to remove, but I'd have to take a look at the original code (from 2011) to be sure.

Hope that helps.

**Comment by reefdog** [comment]
Very interesting, thanks @eyeseast. Since the oEmbed-delivered embed is responsive anyway, does that make this whole conversation unnecessary?

Also, @m4lvin: I just remembered that without the plugin, it's pretty hard to embed notes. You have to know to transform page-anchor-style note URLs that we expose around the platform (e.g., https://www.documentcloud.org/documents/282753-lefler-thesis.html#document/p15/a42227) to the static URL that actually contains the note-specific oEmbed discovery tag (https://www.documentcloud.org/documents/282753-lefler-thesis/annotations/42227.html). That's one of the features of the plugin.

**Comment by eyeseast** [comment]
> Since the oEmbed-delivered embed is responsive anyway, does that make this whole conversation unnecessary?

For the most part, probably. For the StateImpact sites, we had a pattern where we'd display posts differently on the index page if they had `wide_assets` (usually showing only a preview, instead of the whole doc viewer). But that may be an edge case that shouldn't concern this plugin.

**Comment by aschweigert** [comment]
are we ok with just removing this? if so, i'll submit a patch.

**Comment by knowtheory** [comment]
Yep, a patch would be lovely and let's do it.

**Comment by reefdog** [comment]
@aschweigert If you happen to have WP 4.8 installed locally, verifying it works on that would be 👍 so we can update the readme. No worries if not.

@knowtheory You need me to help push the patch to the WP plugin repo, or are you setup with that?

**Comment by knowtheory** [comment]
I am not yet set up to do it!

**Comment by reefdog** [comment]
[You're an admin](https://wordpress.org/plugins/documentcloud/advanced/), so all you need to do is clone (or whatever) the [svn repo](https://plugins.svn.wordpress.org/documentcloud/). I should add a `Development` section to the readme, but basically:

1. Make changes
2. When ready to release a new version, do final testing and housekeeping
   - Update changelog in README.md (for GitHub) and readme.txt (for WordPress Plugin thing)
   - Update [version number](https://github.com/documentcloud/wordpress-documentcloud/blob/master/documentcloud.php#L6)
3. Copy documentcloud.php and readme.txt from this repo into SVN repo (at https://plugins.svn.wordpress.org/documentcloud/trunk/)
4. `svn push` and after a few minutes, verify the [update took](https://wordpress.org/plugins/documentcloud/)
5. Back here in GitHub, tag the release (e.g., `v0.4.4`) and bump the [version number](https://github.com/documentcloud/wordpress-documentcloud/blob/master/documentcloud.php#L6) to the next expected version with `-dev` suffix, e.g. `v0.4.5-dev`. Of course this might end up actually being `v0.5.0` or something, that's fine. Just to mark an inflection point.

**Comment by knowtheory** [comment]
Awesome :) Thanks for the instrux.

**Comment by reefdog** [comment]
For sure. Also just noticed README.md slipped into the official plugin svn repo. Feel free to remove it, they use readme.txt.
